<?php
$this->headTitle('Sign in');

//$this->mainMenu()->setActiveItemId('login');

$form->get('username')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Login',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);


$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Password',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Please sign in</h2>
            <?php if ($isLoginError): ?>
                <!--div class="alert alert-warning" role="alert">
                    Incorrect login and/or password.
                    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                </div-->
            <?php endif; ?>
            <div class="form-group">
                <?= $this->formLabel($form->get('username')); ?>
                <?= $this->formElement($form->get('username')); ?>
                <?= $this->formElementErrors($form->get('username')); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('password')); ?>
                <?= $this->formElement($form->get('password')); ?>
                <?= $this->formElementErrors($form->get('password')); ?>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <div class="form-group">
                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            </div>
        </form>
    </div>
</div>