<?php
$this->headTitle('Users');

//$this->mainMenu()->setActiveItemId('users');

/*$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
]);*/
?>

<h1>Manage Users</h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
    </a>
</p>

<table class="table table-striped">

    <tr>
        <!--th>ID</th-->
        <th>Username (Login)</th>
        <th>E-mail</th>
        <th>Date Created</th>
        <!--th>Status</th-->
        <th>Actions</th>
    </tr>

    <?php foreach ($users as $user): ?>

        <tr>
            <!--td><?= $this->escapeHtml($user->getId()); ?></td-->
            <td>
                <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                    <?= $this->escapeHtml($user->getUsername()); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($user->getEmail()); ?></a>
            </td>
            <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>
            <!--td><?= $this->escapeHtml($user->getStatus()); ?></td-->
            <td>
                <a class="btn btn-info" href="<?= $this->url('users',
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                    <span class="glyphicon glyphicon-asterisk"></span> Change Password
                </a>
                <a class="btn btn-danger" href="<?= $this->url('users',
                    ['action'=>'delete', 'id'=>$user->getId()]); ?>"
                    onclick="return confirm('Are you sure you want to delete user information?')">
                    <span class="glyphicon glyphicon-remove"></span> Delete
                </a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>