<?php
$this->headTitle('View User');

/*
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
]);
*/
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th>Username:</th>
                <td><?= $this->escapeHtml($user->getUsername()) ?></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
            </tr>
            <!--tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatus()) ?></td>
            </tr-->
        </table>
    </div>
</div>

<h1>User's Identities:</h1>
<p>
    <a class="btn btn-default" href="
    <?= $this->url('identities', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Identity / Добавить документ
    </a>
</p>

Паспорта пользователя.