<?php
$this->headTitle('View User');

/*
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
]);
*/
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th>Username:</th>
                <td><?= $this->escapeHtml($user->getUsername()) ?></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
            </tr>
            <!--tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatus()) ?></td>
            </tr-->
        </table>
    </div>
</div>

<!-- Test if the User is connected -->
<?php if( $this->identity()->getId() == $user->getId() ): ?>

    <div class="row">
        <div class="col-md-8"><h1>User's Identities:</h1></div>
        <div class="col-md-4 text-right">
            <a class="btn btn-default" href="<?= $this->url('identities', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Identity / Новый документ
            </a>
        </div>
    </div>

    <?php if ( count($user->getIdentities()) > 0 ): ?>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Identity type / Тип</th>
                        <th>Description / Описание</th>
                        <th>Date added / Добавлено</th>
                        <th>Actions</th>
                    </tr>
                    <?php foreach ($user->getIdentities() as $identity): ?>
                        <tr>
                            <td>
                                <a href="<?= $this->url('identities', ['action'=>'view', 'id'=>$identity->getId()]); ?>">
                                    <?= $this->escapeHtml($identity->getIdentType()) ?>
                                </a>
                            </td>
                            <td></td>
                            <td><?= $this->escapeHtml($identity->getDateCreated()) ?></td>

                            <td>
                                <a class="btn btn-info" href="<?= $this->url('identities',
                                    ['action'=>'edit', 'id'=>$identity->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Edit / Редактировать
                                </a>
                                <a class="btn btn-danger" href="<?= $this->url('identities',
                                    ['action'=>'delete', 'id'=>$identity->getId()]); ?>"
                                   onclick="return confirm('Are you sure you want to delete this identity?')">
                                    <span class="glyphicon glyphicon-remove"></span> Delete / Удалить
                                </a>
                            </td>

                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    <?php endif; ?>

<?php else: ?>
    <p>You do not have access to this user documents</p>
<?php endif ?>

