<?php
$this->headTitle('Add Identity');

/*
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'Add User'=>$this->url('users', ['action'=>'add'])
]);
*/

$form->get('identType')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'passport'
]);

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John'
]);

$form->get('surname')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Doe'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Add Identity</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('identType')); ?>
            <?= $this->formElement($form->get('identType')); ?>
            <?= $this->formElementErrors($form->get('identType')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('surname')); ?>
            <?= $this->formElement($form->get('surname')); ?>
            <?= $this->formElementErrors($form->get('surname')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
