<?php
$this->headTitle('Add Identity');

/*
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'Add User'=>$this->url('users', ['action'=>'add'])
]);
*/

$form->get('identityType')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'passport'
]);

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John'
]);

$form->get('surname')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Doe'
]);

$form->get('range')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'1234'
]);

$form->get('identityId')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'9876-V567'
]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>''
]);

$form->get('dateOfIssue')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>''
]);

$form->get('dateOfExpire')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>''
]);

$form->get('authority')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>''
]);

$form->get('isValid')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>''
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Add Identity</h1>

<p>
    Please fill out the following form.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('identityType')); ?>
            <?= $this->formElement($form->get('identityType')); ?>
            <?= $this->formElementErrors($form->get('identityType')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('surname')); ?>
            <?= $this->formElement($form->get('surname')); ?>
            <?= $this->formElementErrors($form->get('surname')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('range')); ?>
            <?= $this->formElement($form->get('range')); ?>
            <?= $this->formElementErrors($form->get('range')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('identityId')); ?>
            <?= $this->formElement($form->get('identityId')); ?>
            <?= $this->formElementErrors($form->get('identityId')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('dateOfIssue')); ?>
            <?= $this->formElement($form->get('dateOfIssue')); ?>
            <?= $this->formElementErrors($form->get('dateOfIssue')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('dateOfExpire')); ?>
            <?= $this->formElement($form->get('dateOfExpire')); ?>
            <?= $this->formElementErrors($form->get('dateOfExpire')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('authority')); ?>
            <?= $this->formElement($form->get('authority')); ?>
            <?= $this->formElementErrors($form->get('authority')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('isValid')); ?>
            <?= $this->formElement($form->get('isValid')); ?>
            <?= $this->formElementErrors($form->get('isValid')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
