<?php
$form = $this->form;
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>
	
<?= $this->formLabel($form->get('Identity type')); ?>
<?= $this->formElement($form->get('identType')); ?>
<?= $this->formElementErrors($form->get('identtype')); ?>                  
	
<?= $this->formLabel($form->get('Name')); ?>
<?= $this->formElement($form->get('name')); ?>
<?= $this->formElementErrors($form->get('name')); ?>
   
<?= $this->formLabel($form->get('Surname')); ?>
<?= $this->formElement($form->get('surname')); ?>
<?= $this->formElementErrors($form->get('surname')); ?>                  
	
<?= $this->formElement($form->get('submit')); ?>
	
<?= $this->form()->closeTag(); ?>

