<?php
$this->headTitle('View Identity');

/*
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
]);
*/
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
    <div class="col-md-6"><h1>View Identity</h1></div>
    <div class="col-md-2 text-right">
        <a class="btn btn-default btn-xs" href="<?= $this->url('users',
            ['action'=>'view', 'id'=>$identity->getUser()->getId()]); ?>">
            <span class="glyphicon glyphicon-list" ></span> List / Все
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($identity->getId()) ?></td>
            </tr>
            <tr>
                <th>Identity type / Тип</th>
                <td><?= $this->escapeHtml($identity->getIdentityTypeAsString()) ?></td>
            </tr>
            <tr>
                <th>Name / Имя</th>
                <td><?= $this->escapeHtml($identity->getName()) ?></td>
            </tr>
            <tr>
                <th>Surname / Фамилия</th>
                <td><?= $this->escapeHtml($identity->getSurname()) ?></td>
            </tr>

            <tr>
                <th>Identity ID / Номер (и серия)</th>
                <td><?= $this->escapeHtml($identity->getidentityId()) ?>
                    (<?= $this->escapeHtml($identity->getRange()) ?>)</td>
            </tr>

            <tr>
                <th>Description / Описание</th>
                <td><?= $this->escapeHtml($identity->getDescription()) ?></td>
            </tr>
            <tr>
                <th>Date of issue / Выдан</th>
                <td><?= $this->escapeHtml($identity->getDateOfIssue()->format('d-m-Y')) ?></td>
            </tr>
            <tr>
                <th>Date of expire / Действителен до</th>
                <td><?= $this->escapeHtml($identity->getDateOfExpire()->format('d-m-Y')) ?></td>
            </tr>
            <tr>
                <th>Authority / Кем выдан</th>
                <td><?= $this->escapeHtml($identity->getAuthority()) ?></td>
            </tr>
            <tr>
                <th>Added / Добавлен в базу</th>
                <td><?= $this->escapeHtml($identity->getDateCreated()->format('d-m-Y')) ?></td>
            </tr>
            <tr>
                <th>Is valid / Действителен</th>
                <td><?= $this->escapeHtml($identity->getIsValidAsString()) ?></td>
            </tr>
        </table>
    </div>
</div>
<p>
    <a class="btn btn-info" href="<?= $this->url('identities',
        ['action'=>'edit', 'id'=>$identity->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit / Редактировать
    </a>
</p>

