<?= $this->doctype() ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('User Identities')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
    <div class="container">
        <div class="row">
            <!-- Заголовок страницы -->
            <div class="col-md-12">
                <div class="app-caption">Identities / Удостоверения личности</div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- Панель навигации -->
                <nav class="navbar navbar-default" role="navigation">
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a href="<?= $this->url('home') ?>">Home</a>
                            </li>
                            <li>
                                <a href="<?= $this->url('users') ?>">Users / Пользователи</a>
                            </li>
                            <li>
                                <?php if ($this->identity()): ?>
                                <a href="<?= $this->url('logout') ?>">Logout / Выйти</a>
                                <?php endif; ?>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- Навигационная цепочка -->
                <!--ol class="breadcrumb">
                    <li class="active">Home</li>
                </ol-->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- Плейсхолдер для содержимого страницы -->
                <?= $this->content; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <hr>
                <p>&copy; 2003 - <?= date('Y') ?> Identity Company. All rights reserved.</p>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
