<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">User Identities app.</span></h1>

    <p>
        Congratulations!
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="<?= $this->url('login') ?>">Log in / Авторизация</a></p>
</div>
